version: "3.1"

volumes:
  postgres-volume:
  pgadmin4-volume:

services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/pgsql
    volumes:
      - postgres-volume:/var/lib/pgsql
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@web.unical.it
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin4-volume:/var/lib/pgadmin
    links:
      - "pgsql:postgres"
    


