
spring:
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"


database:
  uri: "jdbc:postgresql://localhost:5432/bioagridb"
  username: "admin"
  password: "admin"


auth:
  services:
    external:
      google:
        id: "209781809708-5uqvtbr7fs9t4qs3bqnjo54b0rin6kk8.apps.googleusercontent.com"
      facebook:
        id: ""
      twitter:
        id: ""


payments:
  services:
    external:
      paypal:
        id: "AUDWsdqYEuaWsjEFpN0TLd8Ej_HeeuQ_eAsmG65RBbAcknkPpqkk4D0joMdjUtEm_uj0qYJ8f5886gP1"
        secret: ""

server:
  error:
    whitelabel:
      enabled: false


logging:
  level:
    "web" : OFF
    "it.bioagri" : TRACE


springdoc:
  api-docs:
    path: "/api/public/v3/api-docs"
  swagger-ui:
    path: "/api/public/v3/api-docs-ui"
    disable-swagger-default-url: true
    syntax-highlight:
      activated: true
    operations-sorter: "method"