
spring:
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"


database:
  uri: "jdbc:postgresql://localhost:5432/bioagridb"
  username: "admin"
  password: "admin"


server:
  error:
    whitelabel:
      enabled: false


logging:
  level:
    "web" : TRACE
    "it.bioagri" : TRACE


springdoc:
  api-docs:
    path: "/api/public/v3/api-docs"
  swagger-ui:
    path: "/api/public/v3/api-docs-ui"
    disable-swagger-default-url: true